# Generated by Django 2.2.4 on 2019-09-29 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='path',
            field=models.CharField(default=1, max_length=128, unique=True, verbose_name='菜单URL'),
            preserve_default=False,
        ),
    ]
