# Generated by Django 2.2.4 on 2019-09-30 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_auto_20190929_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='is_show',
            new_name='hidden',
        ),
    ]
